/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashss.se.mctracker;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main method printing Hello World.
     *
     * @param args string array for main method.
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
