Resources:
  PlayerCharactersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: player_characters
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
